name: Cucumber Tests

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0 # Change this to your desired Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Run Cucumber tests headlessly
      env:
        HEADLESS: true
      run: |
        if [ "$HEADLESS" = "true" ]; then
          export DISPLAY=:99
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        fi
        cucumber
